# Python Numpy Arrays

In [ ]:
## import the liberary

In [1]:
import numpy as np

In [3]:
lst=[1,2,3,4,5,6]
arr=np.array(lst)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(6,)

In [7]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,5,6,8,9]

arr1=np.array([lst1,lst2,lst3])

In [8]:
arr1.shape

(3, 5)

In [9]:
arr

array([1, 2, 3, 4, 5, 6])

In [10]:
## indexing

arr[3]

4

In [11]:
arr[3]=5

In [12]:
arr

array([1, 2, 3, 5, 5, 6])

In [14]:
arr[1:3]

array([2, 3])

In [16]:
arr[-2]

5

In [17]:
arr[:-1]

array([1, 2, 3, 5, 5])

In [18]:
arr[::-1]

array([6, 5, 5, 3, 2, 1])

In [19]:
arr[::]

array([1, 2, 3, 5, 5, 6])

In [20]:
arr[::-2]

array([6, 5, 2])

In [21]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 5, 6, 8, 9]])

In [30]:
arr1[:,3:].shape

(3, 2)

In [23]:
arr1[:,1]

array([2, 3, 5])

In [25]:
arr1[2,3]

8

In [26]:
arr1[1:,1:3]

array([[3, 4],
       [5, 6]])

In [27]:
arr1[1:,3:6]

array([[5, 6],
       [8, 9]])

In [31]:
##EDA point of view
arr

array([1, 2, 3, 5, 5, 6])

In [33]:
arr<=2

array([ True,  True, False, False, False, False])

In [35]:
arr[arr<=2]

array([1, 2])

In [36]:
arr1.shape

(3, 5)

In [37]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 5],
       [6, 8, 9]])

In [40]:
## mechanism to creat an arrray

np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [41]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [42]:
arr*arr

array([ 1,  4,  9, 25, 25, 36])

In [43]:
arr1 *2

array([[ 2,  4,  6,  8, 10],
       [ 4,  6,  8, 10, 12],
       [ 6, 10, 12, 16, 18]])

In [44]:
arr1*arr1

array([[ 1,  4,  9, 16, 25],
       [ 4,  9, 16, 25, 36],
       [ 9, 25, 36, 64, 81]])

In [45]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
np.random.randint(10,50,7)

array([29, 10, 21, 37, 45, 45, 11])

In [52]:
np.random.randn(5,6)

array([[-0.0686717 ,  1.48048247, -0.59707508, -0.28203652,  1.02232204,
         0.44369001],
       [ 0.76604827,  1.01060567,  0.40610788,  0.57838356, -1.89442218,
        -0.03016159],
       [-2.42805448, -0.16262258, -0.27895267,  0.42006246,  0.56803201,
         1.66574004],
       [ 0.95861563, -0.96425012,  0.50171288,  0.06871755,  3.22077849,
         0.68725033],
       [ 0.57376246, -0.1967204 , -1.46898467,  0.14564505,  0.18243476,
         0.49376672]])

In [58]:
np.random.random_sample((6,8))

array([[0.84606763, 0.46206166, 0.93197119, 0.1414241 , 0.55402886,
        0.08500815, 0.33712107, 0.14831927],
       [0.59150877, 0.9249954 , 0.19956104, 0.15881086, 0.26516148,
        0.4366469 , 0.74862864, 0.19389714],
       [0.83579437, 0.42630375, 0.87898887, 0.31772842, 0.37084327,
        0.59506847, 0.75875257, 0.67604765],
       [0.00683129, 0.33499262, 0.61815845, 0.78304891, 0.13925217,
        0.65230706, 0.55748963, 0.80300801],
       [0.55984353, 0.9499001 , 0.07240693, 0.34554894, 0.77442213,
        0.79397974, 0.47486123, 0.82456268],
       [0.69640841, 0.04261368, 0.28093401, 0.01921675, 0.86616806,
        0.0391158 , 0.18966205, 0.35572653]])